import type { Insight } from '~/types/site'

export const insights: Insight[] = [
  {
    id: 'in_01',
    slug: 'category-sameness-is-a-choice',
    title: 'Category Sameness Is a Choice, Not a Constraint',
    category: 'Brand Strategy',
    tags: ['branding', 'positioning'],
    excerpt: 'Most categories look the same because most brands make the same safe choices — not because the category demands it.',
    content: 'Most categories look the same because most brands make the same safe choices — not because the category demands it. When we start a positioning project, the first exercise is always a “category convention” audit: what do the top ten competitors all agree on, whether they realize it or not? Colour palettes converge. Tone of voice converges. Even photography style converges. The opportunity is almost never in a wild new territory — it’s in the convention nobody has bothered to question.',
    author: 'Priya Nair',
    date: '2026-07-14',
    readingTime: 6,
    coverColor: '#2A9D8F',
    featured: true,
    seo: { title: 'Category Sameness Is a Choice — 24 Seven Insights', description: 'Why most category conventions are habits, not requirements.', ogImage: '/og/insight-sameness.jpg', schemaType: 'Article' }
  },
  {
    id: 'in_02',
    slug: 'the-90-second-rule-for-launch-films',
    title: 'The 90-Second Rule for Launch Films',
    category: 'Creative Production',
    tags: ['production', 'campaigns'],
    excerpt: 'The best launch films earn every one of their ninety seconds. Here’s how we structure them.',
    content: 'The best launch films earn every one of their ninety seconds. Here’s how we structure them: the first ten seconds are not allowed to mention the product. The next thirty establish a human stake worth caring about. Only in the back half does the product enter — as the resolution to a problem the audience already feels, not as an ingredient list of features. Brands that break this order almost always test worse, even when every individual shot is beautiful.',
    author: 'Sasha Kovalenko',
    date: '2026-06-02',
    readingTime: 5,
    coverColor: '#E63946',
    featured: true,
    seo: { title: 'The 90-Second Rule for Launch Films — 24 Seven Insights', description: 'How we structure launch films that earn attention.', ogImage: '/og/insight-90-second.jpg', schemaType: 'Article' }
  },
  {
    id: 'in_03',
    slug: 'designing-digital-products-like-brand-experiences',
    title: 'Designing Digital Products Like Brand Experiences',
    category: 'Digital',
    tags: ['product design', 'ux'],
    excerpt: 'The gap between “on-brand” and “usable” closes the moment brand and product designers share one backlog.',
    content: 'The gap between “on-brand” and “usable” closes the moment brand and product designers share one backlog. Most brand erosion in digital products doesn’t happen at launch — it happens six months later, in the growth-team A/B test that quietly strips out the typography and motion that made the product feel distinctive in the first place. The fix isn’t a stricter guidelines PDF; it’s embedding a brand-literate designer inside the product team permanently.',
    author: 'Jonah Reyes',
    date: '2026-05-19',
    readingTime: 7,
    coverColor: '#457B9D',
    featured: true,
    seo: { title: 'Designing Digital Products Like Brand Experiences — 24 Seven Insights', description: 'Why brand and product design need one backlog, not two.', ogImage: '/og/insight-digital-products.jpg', schemaType: 'Article' }
  },
  {
    id: 'in_04',
    slug: 'why-heritage-brands-should-modernize-slowly',
    title: 'Why Heritage Brands Should Modernize Slowly',
    category: 'Brand Identity',
    tags: ['branding', 'heritage'],
    excerpt: 'Modernizing a heritage brand is a trust exercise, and trust doesn’t survive a single dramatic reveal.',
    content: 'Modernizing a heritage brand is a trust exercise, and trust doesn’t survive a single dramatic reveal. The brands that get this right — the ones whose most loyal customers barely notice the identity has changed at all — almost always ship the modernization in stages, over eighteen to twenty-four months, letting each change earn its place before the next one lands.',
    author: 'Nadia Ferreira',
    date: '2026-04-08',
    readingTime: 5,
    coverColor: '#3D405B',
    featured: false,
    seo: { title: 'Why Heritage Brands Should Modernize Slowly — 24 Seven Insights', description: 'Modernization as a trust exercise, not a single reveal.', ogImage: '/og/insight-heritage.jpg', schemaType: 'Article' }
  },
  {
    id: 'in_05',
    slug: 'zero-budget-distribution-is-a-design-constraint',
    title: 'Zero-Budget Distribution Is a Design Constraint, Not an Excuse',
    category: 'Campaigns',
    tags: ['campaigns', 'advocacy'],
    excerpt: 'When there’s no media budget, the creative brief has to include distribution as a design requirement from day one.',
    content: 'When there’s no media budget, the creative brief has to include distribution as a design requirement from day one — not something the media team solves after the work ships. That means designing every asset to be remixable, quotable, and screenshot-ready before a single execution is finalized.',
    author: 'Marcus Webb',
    date: '2026-03-11',
    readingTime: 4,
    coverColor: '#023047',
    featured: false,
    seo: { title: 'Zero-Budget Distribution Is a Design Constraint — 24 Seven Insights', description: 'Designing creative for a zero-paid-media distribution model.', ogImage: '/og/insight-zero-budget.jpg', schemaType: 'Article' }
  },
  {
    id: 'in_06',
    slug: 'the-content-engine-vs-the-campaign-moment',
    title: 'The Content Engine vs. the Campaign Moment',
    category: 'Social Media',
    tags: ['social', 'content strategy'],
    excerpt: 'Always-on content and campaign spikes need different success metrics — and different creative teams.',
    content: 'Always-on content and campaign spikes need different success metrics — and often different creative teams. The always-on engine is judged on consistency and voice; the campaign spike is judged on reach and disruption. Conflating the two usually means the always-on content gets held to an impossible creative bar, and the team burns out trying to make every Tuesday post feel like a launch.',
    author: 'Theo Bergström',
    date: '2026-02-20',
    readingTime: 5,
    coverColor: '#264653',
    featured: false,
    seo: { title: 'The Content Engine vs. the Campaign Moment — 24 Seven Insights', description: 'Why always-on content and campaign spikes need different metrics.', ogImage: '/og/insight-content-engine.jpg', schemaType: 'Article' }
  }
]
